[ARM32:STM32] Add _sbrk function for STM32
This patch adds _sbrk function for STM32 for avoiding error when compile
it with AT device support:
/usr/lib/gcc/arm-none-eabi/9.2.0/../../../../arm-none-eabi/bin/ld:
/usr/lib/gcc/arm-none-eabi/9.2.0/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/libc.a(lib_a-sbrkr.o):
in function `_sbrk_r':
/builddir/build/BUILD/newlib-3.1.0/build-newlib/arm-none-eabi/thumb/v7e-m+fp/hard/newlib/libc/reent/../../../../../../../../newlib/libc/reent/sbrkr.c:51:
undefined reference to `_sbrk'
collect2: error: ld returned 1 exit status
scons: *** [rtthread.elf] Error 1
scons: building terminated because of errors.

Signed-off-by: Fu Wei <wefu@redhat.com>