There is no problem to create hello.mo with default compiler on Debian-9.5/amd64.
But building hello.mo with i386-elf-gcc (5.5.0) cross compiler on
OpenBSD-6.3/amd64, undefined reference to 'rt_kprintf' error occurs.

To avoid this error, "compile and link" process needs to be divided to
simply "compile" and "link".

On Debian-9.5, both previous and current method produces same hello.mo.

We have to improve disk image creation (Linux dependent),
this is a future homework.