ci: remove spell_check
We often get wrong report when documentation related are
changed, such as:

```
Getting action download info
Error: This request has been automatically failed because
it uses a deprecated version of `actions/download-artifact: v3`.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/.
This request has been automatically failed because it uses
a deprecated version of `actions/upload-artifact: v3`.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

Just remove this action till now.

Signed-off-by: Chen Wang <unicorn_wang@outlook.com>